[package]
name = "ord"
description = "Bitcoin satoshi ordinal number utility"
version = "0.0.3"
license = "CC0-1.0"
edition = "2021"
autotests = false

[dependencies]
anyhow = { version = "1.0.56", features = ["backtrace"] }
async-rustls = "0.2.0"
axum = "0.5.6"
axum-server = "0.4.0"
bitcoin = "0.28.1"
bitcoincore-rpc = "0.15.0"
boilerplate = { version = "0.0.2", features = ["axum"] }
chrono = "0.4.19"
clap = { version = "3.1.0", features = ["derive"] }
ctrlc = "3.2.1"
derive_more = "0.99.17"
dirs = "4.0.0"
env_logger = "0.9.0"
futures = "0.3.21"
http = "0.2.6"
log = "0.4.14"
mime_guess = "2.0.4"
rayon = "1.5.1"
redb = { version = "0.5.0", git = "https://github.com/cberner/redb", branch = "master" }
rust-embed = "6.4.0"
rustls-acme = "0.3.0"
serde = { version = "1.0.137", features = ["derive"] }
serde_cbor = "0.11.2"
serde_json = "1.0.81"
tokio = { version = "1.17.0", features = ["rt-multi-thread"] }
tokio-stream = "0.1.9"
tokio-util = {version = "0.7.3", features = ["compat"] }
tower = "0.4.13"
tower-http = { version = "0.3.3", features = ["cors"] }

[dependencies.bdk]
git = "https://github.com/terror/bdk.git"
branch = "dust-limit"
version = "0.20.1-dev"
features = ["rpc", "keys-bip39", "sqlite"]

[dev-dependencies]
executable-path = "1.0.0"
hex = "0.4.3"
log = "0.4.14"
nix = "0.24.1"
pretty_assertions = "1.2.1"
regex = "1.6.0"
reqwest = { version = "0.11.10", features = ["blocking"] }
tempfile = "3.2.0"
unindent = "0.1.7"

[[test]]
name = "integration"
path = "tests/lib.rs"

[build-dependencies]
pulldown-cmark = "0.9.2"
