[package]
name = "bitcoin-atoms"
description = "Bitcoin atom utilies"
version = "0.0.0"
license = "CC0-1.0"
edition = "2021"

[dependencies]
bitcoin = "0.27.1"
executable-path = "1.0.0"
redb = "0.0.3"
structopt = "0.3.25"
tempfile = "3.2.0"
