[package]
name = "bitcoin-atoms"
description = "Bitcoin atom utilies"
version = "0.0.0"
license = "CC0-1.0"
edition = "2021"

[dependencies]
bitcoin = "0.27.1"
bitcoincore-rpc = "0.14.0"
dirs = "4.0.0"
reqwest = { version = "0.11.7", features = ["blocking", "json"]}
serde = { version = "1.0.131", features = ["derive"] }
structopt = "0.3.25"
