[package]
name = "ord"
description = "Bitcoin ordinal theory utility"
version = "0.3.0"
license = "CC0-1.0"
edition = "2021"
autotests = false
homepage = "https://github.com/casey/ord"
repository = "https://github.com/casey/ord"
autobins = false

[workspace]
members = [".", "fuzz", "test-bitcoincore-rpc"]

[dependencies]
anyhow = { version = "1.0.56", features = ["backtrace"] }
axum = "0.6.1"
axum-server = "0.4.0"
bech32 = "0.9.1"
bip39 = "1.0.1"
bitcoin = { version = "0.29.1", features = ["rand"] }
boilerplate = { version = "0.2.3", features = ["axum"] }
chrono = "0.4.19"
clap = { version = "3.1.0", features = ["derive"] }
ctrlc = "3.2.1"
derive_more = "0.99.17"
dirs = "4.0.0"
env_logger = "0.10.0"
futures = "0.3.21"
hex = "0.4.3"
html-escaper = "0.2.0"
http = "0.2.6"
indicatif = "0.17.1"
lazy_static = "1.4.0"
log = "0.4.14"
mime = "0.3.16"
mime_guess = "2.0.4"
miniscript = "9.0.0"
ord-bitcoincore-rpc = { git = "https://github.com/casey/rust-bitcoincore-rpc", branch = "ord" }
redb = "0.11.0"
regex = "1.6.0"
rss = "2.0.1"
rust-embed = "6.4.0"
rustls = "0.20.6"
rustls-acme = { version = "0.5.0", features = ["axum"] }
serde = { version = "1.0.137", features = ["derive"] }
serde_json = { version = "1.0.81" }
sys-info = "0.9.1"
tempfile = "3.2.0"
tokio = { version = "1.17.0", features = ["rt-multi-thread"] }
tokio-stream = "0.1.9"
tokio-util = {version = "0.7.3", features = ["compat"] }
tower-http = { version = "0.3.3", features = ["set-header"] }

[dev-dependencies]
executable-path = "1.0.0"
pretty_assertions = "1.2.1"
reqwest = { version = "0.11.10", features = ["blocking"] }
test-bitcoincore-rpc = { path = "test-bitcoincore-rpc" }
unindent = "0.1.7"

[[bin]]
name = "ord"
path = "src/bin/main.rs"

[lib]
name = "ord"
path = "src/lib.rs"

[[test]]
name = "integration"
path = "tests/lib.rs"

[build-dependencies]
pulldown-cmark = "0.9.2"

[patch.crates-io]
jsonrpc = { git = "https://github.com/apoelstra/rust-jsonrpc.git", rev = "64b58797dd517c4de0cec769ff5652220801fe18" }
redb = { git = "https://github.com/casey/redb.git", branch = "ord" }
