[package]
name = "sat-tracker"
description = "Satoshi tracker"
version = "0.0.0"
license = "CC0-1.0"
edition = "2021"
autotests = false

[dependencies]
bitcoin = "0.27.1"
env_logger = "0.9.0"
executable-path = "1.0.0"
log = "0.4.14"
redb = "0.0.3"
structopt = "0.3.25"
tempfile = "3.2.0"

[[test]]
name = "integration"
path = "tests/integration.rs"
