[package]
name = "ord"
description = "Bitcoin satoshi ordinal number utility"
version = "0.0.0"
license = "CC0-1.0"
edition = "2021"
autotests = false

[dependencies]
anyhow = { version = "1.0.56", features = ["backtrace"] }
axum = "0.4.8"
axum-server = "0.3.3"
bitcoin = "0.27.1"
bitcoincore-rpc = "0.14.0"
chrono = "0.4.19"
clap = { version = "3.1.0", features = ["derive"] }
ctrlc = "3.2.1"
derive_more = "0.99.17"
dirs = "4.0.0"
env_logger = "0.9.0"
executable-path = "1.0.0"
integer-cbrt = "0.1.2"
integer-sqrt = "0.1.5"
jsonrpc = "0.12.1"
lazy_static = "1.4.0"
log = "0.4.14"
ord-lmdb-zero = "0.4.5"
rayon = "1.5.1"
redb = { version = "0.0.5", optional = true }
tokio = { version = "1.17.0", features = ["rt-multi-thread"] }

[dev-dependencies]
criterion = "0.3.5"
hex = "0.4.3"
jsonrpc-core = "18.0.0"
jsonrpc-core-client = "18.0.0"
jsonrpc-derive = "18.0.0"
jsonrpc-http-server = "18.0.0"
nix = "0.23.1"
regex = "1.5.4"
reqwest = { version = "0.11.9", features = ["blocking"] }
tempfile = "3.2.0"
unindent = "0.1.7"

[[test]]
name = "integration"
path = "tests/integration.rs"

[[bench]]
name = "index"
harness = false
