name: Book

on:
  pull_request:
    branches:
    - master
  push:
    branches:
    - master

defaults:
  run:
    shell: bash

jobs:
  book:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.0.0

    - uses: peaceiris/actions-mdbook@v1
      with:
        mdbook-version: latest

    - name: Install mdbook-linkcheck
      run: |
        mkdir -p mdbook-linkcheck
        cd mdbook-linkcheck
        wget https://github.com/Michael-F-Bryan/mdbook-linkcheck/releases/latest/download/mdbook-linkcheck.x86_64-unknown-linux-gnu.zip
        unzip mdbook-linkcheck.x86_64-unknown-linux-gnu.zip
        chmod +x mdbook-linkcheck
        pwd >> $GITHUB_PATH

    - run: mdbook build book

    - name: Deploy Pages
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/master'
      with:
        github_token: ${{secrets.GITHUB_TOKEN}}
        publish_branch: gh-pages
        publish_dir: book/build/html
