name: Build Docs

on:
  pull_request:
    branches:
    - master

defaults:
  run:
    shell: bash

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.0.0
    - uses: shalzz/zola-deploy-action@v0.16.1
      env:
        BUILD_DIR: docs
        BUILD_ONLY: true
        BUILD_FLAGS: --drafts
